services:
  php:
    container_name: marketplace_symfony_php
    build:
      context: .
      dockerfile: dockerfile
    command: php-fpm  # Здесь должно быть указано php-fpm или другая нужная команда
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database
    
  nginx:
    container_name: marketplace_symfony_nginx
    image: nginx:1.26.2
    restart: always
    volumes:
      - ./docker/nginx/logs:/var/log/nginx
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf    
    depends_on: 
      - database
    ports: 
      - 127.0.0.1:6000:80
    environment:
      MYSQL_ROOT_PASSWORD: root         # Пароль для пользователя root
      MYSQL_DATABASE: marketplace_symfony            # Имя базы данных, которая будет создана при старте
      MYSQL_USER: root        # Имя пользователя
      MYSQL_PASSWORD: root

  database:
    image: mariadb:10.5.2
    container_name: marketplace_symfony_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=marketplace_symfony
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
    ports:
      - 127.0.0.1:3307:80